import pygame
WINDOWWIDTH = 1600
WINDOWHEIGHT = 1600
WINDOWTOBOARDRATIO = 1
SQUARECOUNT = 8
BOARDSIDELENGTH = WINDOWWIDTH * WINDOWTOBOARDRATIO
SQUARESIZE = int(BOARDSIDELENGTH / SQUARECOUNT)
BOARDPOSX = (WINDOWWIDTH - BOARDSIDELENGTH) / 2
BOARDPOSY = (WINDOWHEIGHT - BOARDSIDELENGTH) / 2
EMPTY = None
#COLORS
DARKRED = (102, 0, 0)
LIGHTBROWN = (185, 122, 87)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)